language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

install:
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpunit -c ./phpunit.xml --coverage-text --strict --verbose --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)